### ISSUE TITLE
Bioconda update to v0.7.0 is blocked

### ISSUE THREAD

**Issue by jhahnfeld** [althonos/pyhmmer#29] opened 2022-12-13 09:05 UTC
Hi Martin,

something is blocking the pyhmmer update from version 0.6.3 to 0.7.0 on [bioconda](https://github.com/bioconda/bioconda-recipes/pull/38226).

Could you have a look at what is blocking the update?

Thanks,

Julian

**Comment by althonos** [comment] 2022-12-13 12:48
Hi Julian, from what I read the update is blocked because of a compilation issue for Python 3.8 on MacOS, this is particularly hard to debug since I don't have a Mac, and that the compilation works as intended in the GitHub Actions runners I use for testing... For the time being, you can just `pip install pyhmmer` in your `conda` environment to get version `0.7.0`.

**Comment by althonos** [comment] 2022-12-15 15:48
Should be fixed now!

**Closed by althonos** 2022-12-15 15:48 UTC
Labels: building, external

**Comment by jhahnfeld** [comment] 2022-12-19 13:16
Thank you very much. Everything is working fine now.
